"""empty message

Revision ID: 2239fbed891b
Revises: None
Create Date: 2015-07-29 19:22:49.714862

"""

# revision identifiers, used by Alembic.
revision = '2239fbed891b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
