"""empty message

Revision ID: 278e4377f80d
Revises: None
Create Date: 2014-12-20 07:17:03.645000

"""

# revision identifiers, used by Alembic.
revision = '278e4377f80d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
