"""empty message

Revision ID: 28b9023f42ab
Revises: None
Create Date: 2014-12-12 22:51:18.205402

"""

# revision identifiers, used by Alembic.
revision = '28b9023f42ab'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor__video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('video_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_name'], [u'actor.name'], ),
    sa.ForeignKeyConstraint(['video_name'], [u'video.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'actor', sa.Column('active_year', sa.Integer(), nullable=True))
    op.add_column(u'actor', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column(u'actor', sa.Column('body_size', sa.String(length=255), nullable=True))
    op.add_column(u'actor', sa.Column('similar_actor', sa.String(length=255), nullable=True))
    op.drop_column(u'actor', 'id')
    op.create_foreign_key(None, 'actor_review', 'actor', ['actor_name'], ['name'])
    op.create_foreign_key(None, 'actor_review', 'user', ['user_email'], ['email'])
    op.drop_column(u'actor_review', 'actorID')
    op.drop_column(u'actor_review', 'userID')
    op.drop_column(u'actor_review', 'created')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'actor_review', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.add_column(u'actor_review', sa.Column('userID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'actor_review', sa.Column('actorID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actor_review', type_='foreignkey')
    op.drop_constraint(None, 'actor_review', type_='foreignkey')
    op.add_column(u'actor', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column(u'actor', 'similar_actor')
    op.drop_column(u'actor', 'body_size')
    op.drop_column(u'actor', 'age')
    op.drop_column(u'actor', 'active_year')
    op.drop_table('actor__video')
    ### end Alembic commands ###
