"""empty message

Revision ID: 302533209f4
Revises: None
Create Date: 2015-06-29 02:18:51.929350

"""

# revision identifiers, used by Alembic.
revision = '302533209f4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hash_actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actorName', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actorName'], [u'actor.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hash_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoName', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['videoName'], [u'video.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hash_video')
    op.drop_table('hash_actor')
    ### end Alembic commands ###
