"""empty message

Revision ID: 36a3d97414ff
Revises: None
Create Date: 2015-07-01 21:43:23.518758

"""

# revision identifiers, used by Alembic.
revision = '36a3d97414ff'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_actor', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('rating_video', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_video', 'created')
    op.drop_column('rating_actor', 'created')
    ### end Alembic commands ###
