"""empty message

Revision ID: 3b69668b76a1
Revises: None
Create Date: 2015-07-21 00:27:49.664584

"""

# revision identifiers, used by Alembic.
revision = '3b69668b76a1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
