"""empty message

Revision ID: 4b34401a35d9
Revises: None
Create Date: 2015-05-14 11:27:47.616280

"""

# revision identifiers, used by Alembic.
revision = '4b34401a35d9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
