"""empty message

Revision ID: 551bf6ca9661
Revises: None
Create Date: 2015-07-06 04:11:01.722499

"""

# revision identifiers, used by Alembic.
revision = '551bf6ca9661'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
